title: Project1
description: Project1
url: "https://wizards-of-things.github.io/project1"
project: test1
markdown: kramdown
permalink: /:title
google_analytics: UA-
youtube: https://www.youtube.com/user/
github:
  repository_url: https://github.com/wizard-of-things/project1
  raw_content_url: https://raw.githubusercontent.com/wizard-of-things/project1/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "scripts", "firmware"]
include: ["_data"]
